package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/trackhub/api/graph/generated"
	"github.com/trackhub/api/graph/model"
)

// ListTracks is the resolver for the listTracks field.
func (r *queryResolver) ListTracks(ctx context.Context, skipTracks []string, neLat float64, swLat float64, neLon float64, swLon float64) (*model.TrackListResult, error) {
	result := &model.TrackListResult{}

	tracks := make([]*model.Track, 0, 10)

	gormTracks, err := r.TrackRepository().FindAllPublicNotInId(
		ctx,
		skipTracks,
		11,
		neLat,
		swLat,
		neLon,
		swLon,
	)

	if err != nil {
		log.Println("Unalbe to fetch tracks", err)
		return nil, errors.New("Unable to fetch tracs")
	}

	trackCount := 0
	for _, gormTrack := range gormTracks {
		trackCount += 1
		if trackCount > 10 {
			result.Status = 1
			break
		}

		track := &model.Track{
			ID:       gormTrack.ID,
			SlugOrID: gormTrack.SlugOrId(),
			Type:     &gormTrack.Type,
			Versions: make([]*model.TrackVersion, 0),
		}

		for _, trackVersion := range gormTrack.TrackVersions {
			track.Versions = append(track.Versions, &model.TrackVersion{
				ID: trackVersion.ID,
			})
		}

		for _, optimizedPoint := range gormTrack.OptimizedPoints {
			track.OptimizedPoints = append(track.OptimizedPoints, &model.Point{
				Lat: optimizedPoint.Lat,
				Lng: optimizedPoint.Lng,
			})
		}

		tracks = append(
			tracks,
			track,
		)
	}

	result.Tracks = tracks

	return result, nil
}

// ListPlaces is the resolver for the listPlaces field.
func (r *queryResolver) ListPlaces(ctx context.Context, skipPlaces []string) ([]*model.Place, error) {
	panic(fmt.Errorf("not implemented: ListPlaces - listPlaces"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
