# GraphQL schema example
#
# https://gqlgen.com/getting-started/

enum Locale {
  en
  bg
}

type User {
  id: ID!
  name: String!
}

type Point {
  lat: Float!
  lng: Float!
}

type Query {
  track(idOrSlug: String!): Track!

  listTracks(
    skipTracks: [String!]
    neLat: Float!
    swLat: Float!
    neLon: Float!
    swLon: Float!

  ): TrackListResult!

  latestTracks(type: Int!, locale: Locale): [Track!]!

  listPlaces(
    skipPlaces: [String!]
    neLat: Float!
    swLat: Float!
    neLon: Float!
    swLon: Float!
  ): PlaceListResult!
}

type Place {
  attraction: Boolean!
  id: String!
  slugOrId: String!
  name: String
  icon: String
  lat: Float!
  lng: Float!
}

type Track {
  id: String!
  name: String
  slugOrId: String!
  points: [Point!]
  type: Int!
  versions: [TrackVersion!]
  optimizedPoints: [[Point!]]
}

type TrackVersion {
  id: String!
}

type PlaceListResult {
  places: [Place!]!
  status: Int!
}

type TrackListResult {
  tracks: [Track]!
  status: Int!
}
