package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/trackhub/api/graph/generated"
	"github.com/trackhub/api/graph/model"
	"github.com/trackhub/api/service/mapper"
)

// Track is the resolver for the track field.
func (r *queryResolver) Track(ctx context.Context, idOrSlug string) (*model.Track, error) {
	gormTrack, err := r.TrackRepository().GetBySlugOrId(context.TODO(), idOrSlug)
	if err != nil {
		fmt.Println("Error during getting track with id "+idOrSlug+": ", err.Error())
		return nil, errors.New("unable to find the track")
	}

	return mapper.GormTrackToGraphTrack(*gormTrack), nil
}

// ListTracks is the resolver for the listTracks field.
func (r *queryResolver) ListTracks(ctx context.Context, skipTracks []string, neLat float64, swLat float64, neLon float64, swLon float64) (*model.TrackListResult, error) {
	result := &model.TrackListResult{}

	const queryLimit = 10

	tracks := make([]*model.Track, 0, queryLimit)

	gormTracks, err := r.TrackRepository().FindAllPublicNotInId(
		ctx,
		skipTracks,
		queryLimit+1,
		neLat,
		swLat,
		neLon,
		swLon,
	)

	if err != nil {
		log.Println("Unalbe to fetch tracks", err)
		return nil, errors.New("Unable to fetch tracs")
	}

	trackCount := 0
	for _, gormTrack := range gormTracks {
		trackCount += 1
		if trackCount > queryLimit {
			result.Status = 2
			break
		}

		tracks = append(
			tracks,
			mapper.GormTrackToGraphTrack(gormTrack),
		)
	}

	result.Tracks = tracks

	return result, nil
}

// LatestTracks is the resolver for the latestTracks field.
func (r *queryResolver) LatestTracks(ctx context.Context, typeArg int, locale *model.Locale) ([]*model.Track, error) {
	tracks := make([]*model.Track, 0, 10)

	gormTracks, err := r.TrackRepository().FindLatest(context.TODO(), typeArg, 10)
	if err != nil {
		log.Println("Unable to fetch latest tracks", err)
		return nil, errors.New("Unable to fetch tracks")
	}

	for _, gormTrack := range gormTracks {
		tracks = append(
			tracks,
			mapper.GormTrackToGraphTrack(gormTrack),
		)
	}

	return tracks, nil
}

// ListPlaces is the resolver for the listPlaces field.
func (r *queryResolver) ListPlaces(ctx context.Context, skipPlaces []string, neLat float64, swLat float64, neLon float64, swLon float64) (*model.PlaceListResult, error) {
	result := &model.PlaceListResult{}

	const queryLimit = 100

	places := make([]*model.Place, 0, queryLimit)

	gormPlaces, err := r.PlaceRepository().FindAllPublicNotInId(
		ctx,
		skipPlaces,
		queryLimit+1,
		neLat,
		swLat,
		neLon,
		swLon,
	)

	if err != nil {
		log.Println("Unalbe to fetch places", err)
		return nil, errors.New("Unable to fetch places")
	}

	placesCount := 0
	for _, gormPlace := range gormPlaces {
		placesCount += 1
		if placesCount > queryLimit {
			result.Status = 2
			break
		}

		var icon *string
		calculatedIcon, err := r.PlaceImageDetector().DetectImage(int(gormPlace.Type))
		if err == nil {
			icon = &calculatedIcon
		}

		place := &model.Place{
			ID:         gormPlace.ID,
			SlugOrID:   gormPlace.SlugOrId(),
			Name:       &gormPlace.NameEn, // @TODO localize
			Attraction: gormPlace.IsAttraction,
			Icon:       icon,
			Lat:        gormPlace.Lat,
			Lng:        gormPlace.Lng,
		}

		places = append(
			places,
			place,
		)
	}

	result.Places = places

	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
