# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type User {
  id: ID!
  name: String!
}

type Point {
  lat: Float!
  lng: Float!
}

type Query {
  listTracks(
    skipTracks: [String!]
    neLat: Float!
    swLat: Float!
    neLon: Float!
    swLon: Float!

  ): TrackListResult!

  listPlaces(
    skipPlaces: [String!]
  ): [Place!]!
}

type Place {
  attraction: Boolean
  id: String!
  slugOrId: String!
  name: String
  icon: String
  lat: Float
  lng: Float
}

type Track {
  id: String!
  name: String
  slugOrId: String!
  points: [Point!]
  type: Int
  versions: [TrackVersion!]
  optimizedPoints: [Point!]
}

type TrackVersion {
  id: String!
}

type TrackListResult {
  tracks: [Track]!
  status: Int!
}
