Track:
  type: object
  config:
    resolveField: '@=resolver("App\\GraphQL\\Resolver\\My::sayHelloA", [value, info, args])'
    fields:
      nameEn:
        type: String
      id:
        type: String
