Track:
  type: object
  config:
#    resolveField: '@=resolver("DefaultResolver::defaultMethod", [value, info, args])'
    fields:
      id:
        type: String!
      slug:
        type: String
      nameEn:
        type: String
      visibility:
        type: Int!
      optimizedPoints:
        type: "[Point]"
# add resolver
#      createdAt:
#        type: Int
