Track:
  type: object
  config:
    fields:
      id:
        type: 'String!'
      slug:
        type: 'String'
      slugOrId:
        type: 'String!'
      nameEn:
        type: 'String'
      visibility:
        type: 'Int!'
      optimizedPoints:
        type: '[Point]'
