// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Point struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type Track struct {
	ID       string   `json:"id"`
	Name     *string  `json:"name,omitempty"`
	SlugOrID string   `json:"slugOrId"`
	Points   []*Point `json:"points,omitempty"`
	Type     *int     `json:"type,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
