// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Place struct {
	Attraction *bool    `json:"attraction,omitempty"`
	ID         string   `json:"id"`
	SlugOrID   string   `json:"slugOrId"`
	Name       *string  `json:"name,omitempty"`
	Icon       *string  `json:"icon,omitempty"`
	Lat        *float64 `json:"lat,omitempty"`
	Lng        *float64 `json:"lng,omitempty"`
}

type Point struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type Query struct {
}

type Track struct {
	ID       string   `json:"id"`
	Name     *string  `json:"name,omitempty"`
	SlugOrID string   `json:"slugOrId"`
	Points   []*Point `json:"points,omitempty"`
	Type     *int     `json:"type,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
